=== swap-08/mylearnings/Foundation_Retest/section4_XML/Student.xsd
<?xml version="1.0" encoding="iso-8859-9"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!--Definition of Simple Elements-->
  
  <xs:element name="first_name" type="ref_name" />
  <xs:element name="last_name" type="ref_last_name" />
  <xs:element name="mobile_number" type="ref_mobile" />
  <xs:element name="landline_number" type="ref_landline_mobile" />
  <xs:element name="address" type="xs:string" />
  <xs:element name="department_number" type="ref_department_number" />

  <!--Definition of Attrribute-->
  
  <xs:attribute name="stud_id" type="xs:unsignedInt"/>


  <!--Definition of Complex Elements-->

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="name">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="first_name"/>
              <xs:element ref="last_name"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="phone">
          <xs:complexType>
            <xs:choice>
              <xs:element ref="mobile_number"/>
              <xs:element ref="landline_number"/>
            </xs:choice>
          </xs:complexType>
        </xs:element>

        <xs:element ref="address"/>
        <xs:element ref="department_number"/>
      </xs:sequence>
      
      <xs:attribute ref="stud_id" use="required"/>
      
    </xs:complexType>
  </xs:element>

  <!--Definition of Simple Type for Restriction-->


  <!--Restriction on first name
      Name must not contain any integer values-->
  
  <xs:simpleType name="ref_name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]*"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Restriction on last name
      Name must not contain any integer values-->

  <xs:simpleType name="ref_last_name">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]*"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Restriction on mobile number
      mobile number must  contain only 10 decimal values-->
  
  <xs:simpleType name="ref_mobile">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Restriction on landline number
      mobile number must  contain only 10 decimal values-->

  <xs:simpleType name="ref_landline_mobile">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="[0-9]{10}"/>
    </xs:restriction>
  </xs:simpleType>

  <!--Restriction on department number
      department number must  contain only 2 decimal values-->

  <xs:simpleType name="ref_department_number">
    <xs:restriction base="xs:positiveInteger">
      <xs:pattern value="[0-9]{2}"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== swap-08/mylearnings/Foundation_Retest/section4_XML/Student.xml
<?xml version="1.0" encoding="iso-8859-9"?>
<student stud_id="101" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="Student.xsd">
  <name>
    <first_name>Aditya</first_name>
    <last_name>Kadam</last_name>
  </name>
  <phone>
    <mobile_number>9865324710</mobile_number>
  </phone>
  <address>Mumbai</address>
  <department_number>20</department_number>
  
</student>
