=== swap-08/mylearnings/Web_Basics/XML/lab1.5.3/lab5.2.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="empDetails">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="employee">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Ecode" type="xs:unsignedShort" />
              <xs:element name="Ename">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Fname" type="xs:string" />
                    <xs:element name="Lname" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Doj" type="xs:string" />
              <xs:element name="TotalExp" type="xs:unsignedByte" />
              <xs:element name="Department">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Unit" type="xs:string" />
                    <xs:element name="loc" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Designation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="one" />
                    <xs:element name="two" type="xs:string" />
                    <xs:element name="three" />
                    <xs:element name="four" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Sal" type="xs:unsignedShort" />
              <xs:element name="Grade">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="a" type="xs:string" />
                    <xs:element name="b" type="xs:string" />
                    <xs:element name="c" />
                    <xs:element name="d" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== swap-08/mylearnings/Web_Basics/XML/lab1.5.3/lab5.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<empDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="lab5.2.xsd">
  <employee>
    <Ecode>1111</Ecode>
    <Ename>
      <Fname>Seema</Fname>
      <Lname>Dalvi</Lname>
    </Ename>
    <Doj>09/08/97</Doj>
    <TotalExp>12</TotalExp>
    <Department>
      <Unit>3d</Unit>
      <loc>Mumbai</loc>
    </Department>
    <Designation>
      <one></one>
      <two></two>
      <three></three>
      <four>*</four>
    </Designation>
    <Sal>21000</Sal>
    <Grade>
      <a></a>
      <b>*</b>
      <c></c>
      <d></d>
    </Grade>
  </employee>
  <employee>
    <Ecode>222</Ecode>
    <Ename>
      <Fname>Bharti</Fname>
      <Lname>Mantri</Lname>
    </Ename>
    <Doj>12/02/99</Doj>
    <TotalExp>5</TotalExp>
    <Department>
      <Unit>4a</Unit>
      <loc>Pune</loc>
    </Department>
    <Designation>
      <one></one>
      <two>*</two>
      <three></three>
      <four></four>
    </Designation>
    <Sal>12000</Sal>
    <Grade>
      <a>*</a>
      <b></b>
      <c></c>
      <d></d>
    </Grade>
  </employee>
</empDetails>
