=== swap-08/mylearnings/Web_Basics/classwork_XML/XML Guide/5.4.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<xs:element name="lib" type="eLib"/>

<xs:complexType name="eLib">

<xs:sequence>

<xs:element name="book" type="eBook" maxOccurs="unbounded"/>

</xs:sequence>

</xs:complexType>


<xs:complexType name="eBook" >

<xs:sequence>
<xs:element name="title" type="xs:string"/>
<xs:element name="author" type="xs:string"/>
<xs:element name="publisher" type="xs:string"/>

<xs:element name="cover">

<xs:complexType>
<xs:attribute name="cover_type" type="xs:string" use="required"/>
</xs:complexType>
</xs:element>

<xs:element name="category">
     <xs:complexType>
  <xs:attribute name="cat_type" type="xs:string" use="required"/>
    </xs:complexType>
    </xs:element>
    
<xs:element name="isbn">

<xs:complexType>
  <xs:attribute name="isbn_num" type="xs:string" use="required"/>
    </xs:complexType>
    </xs:element>
    
<xs:element name="rate" >
<xs:complexType>
  <xs:attribute name="rate_val" type="xs:string" use="required"/>
    </xs:complexType>
    </xs:element>
    
<xs:element name="price" type="xs:string"/>

<xs:element name="comments" type="xs:string"/>

</xs:sequence>

 
  
</xs:complexType>

</xs:schema>

=== swap-08/mylearnings/Web_Basics/classwork_XML/XML Guide/5.4.xml
<?xml version="1.0" encoding="UTF-8"?>



<lib xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="5.4.xsd">


<book>
<title>Death to the World</title>
<author>Harris</author>
<publisher>ABC</publisher>
<cover cover_type="Hardbook"></cover>
<category cat_type="Horror"></category>
<isbn isbn_num="z1"></isbn>
<rate rate_val="5"></rate>
<price>$13.97</price>
<comments>Good Luck</comments>

</book>

<book>

<title>Gardens</title>
<author>Steven</author>
<publisher>XYZ</publisher>
<cover cover_type="Softbook"></cover>

<category cat_type="SCI FI"></category>

<isbn isbn_num="z3"></isbn>

<rate rate_val="4"></rate>

<price>$17.97</price>
<comments>Good Luck again</comments>
</book>




</lib>
